### ISSUE TITLE
Failed to install the app.

### ISSUE THREAD

**Issue by 44asad** [AndreiD/xzil-wallet#24]
### Actual Behaviour

App fail to install in my device.
### Expected Behaviour

I expected that i can install and use the app successfully.
### Step to reproduce
* Click On Download Option.
* Go to Playstor
* Cann't install 
#### Information
App version:
Os:Android 6.0.1
Device:Samsung j5
### Recording of the bug

https://youtu.be/Uwy_H-iry-E

**Comment by 44asad** [comment]
@AndreiD
please  review

**Comment by AndreiD** [comment]
hello,

thanks for taking the time to write an issue.
the application is compiled with the **minimum Android version 8.1** 
This is because of the new security protections that android 8.1 has

you theoretically can fork the repo, lower the build target sdk, and build it for you only, it will work or it will work with very few changes in the code.

or try with a newer android version phone
